### ISSUE TITLE
加载权重的时候报错

### ISSUE THREAD

**Issue by Monkeone** [phecy/SSL-FEW-SHOT#2]
Traceback (most recent call last):
  File "D:/框架pytorch/SSL-FEW-SHOT-master/train_protonet.py", line 84, in <module>
    model_detail = torch.load(args.init_weights)
  File "D:\新建文件夹\python\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\新建文件夹\python\lib\site-packages\torch\serialization.py", line 573, in _load
    result = unpickler.load()
  File "D:\新建文件夹\python\lib\site-packages\torch\serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "D:\新建文件夹\python\lib\site-packages\torch\serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "D:\新建文件夹\python\lib\site-packages\torch\serialization.py", line 98, in _cuda_deserialize
    with torch.cuda.device(device):
  File "D:\新建文件夹\python\lib\site-packages\torch\cuda\__init__.py", line 243, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
  File "D:\新建文件夹\python\lib\site-packages\torch\cuda\__init__.py", line 180, in _lazy_init
    _cudart = _load_cudart()
  File "D:\新建文件夹\python\lib\site-packages\torch\cuda\__init__.py", line 77, in _load_cudart
    lib = find_cuda_windows_lib()
  File "D:\新建文件夹\python\lib\site-packages\torch\cuda\__init__.py", line 50, in find_cuda_windows_lib
    out = out.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 3: invalid continuation byte

**Comment by phecy** [comment]
this my cause by run in windows environment, pls just use linux or mac environment.

**Comment by Monkeone** [comment]
thank you，谢谢您的回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"phecy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 晚上10:54
收件人:&nbsp;"phecy/SSL-FEW-SHOT"<SSL-FEW-SHOT@noreply.github.com&gt;;
抄送:&nbsp;"1270843624"<1270843624@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [phecy/SSL-FEW-SHOT] 加载权重的时候报错 (#2)




this my cause by run in windows environment, pls just use linux or mac environment.
